# ---- dev stage ----
FROM node:20-alpine
WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm ci

# Кладём исходники (в рантайме их перекроет bind-mount)
COPY . .

# Настройки для отслеживания файлов в Docker
ENV HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 5173
CMD ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]
